// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/rauban/filedropper/protocol/FileTransfer.proto

package com.rauban.dropandtransfer.protocol;

public final class FileTransfer {
  private FileTransfer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FileDropHeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint64 size = 1;
    boolean hasSize();
    long getSize();
    
    // required bool isDir = 2;
    boolean hasIsDir();
    boolean getIsDir();
    
    // required string resourceName = 3;
    boolean hasResourceName();
    String getResourceName();
  }
  public static final class FileDropHeader extends
      com.google.protobuf.GeneratedMessage
      implements FileDropHeaderOrBuilder {
    // Use FileDropHeader.newBuilder() to construct.
    private FileDropHeader(Builder builder) {
      super(builder);
    }
    private FileDropHeader(boolean noInit) {}
    
    private static final FileDropHeader defaultInstance;
    public static FileDropHeader getDefaultInstance() {
      return defaultInstance;
    }
    
    public FileDropHeader getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rauban.dropandtransfer.protocol.FileTransfer.internal_static_com_rauban_filedropper_protocol_FileDropHeader_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rauban.dropandtransfer.protocol.FileTransfer.internal_static_com_rauban_filedropper_protocol_FileDropHeader_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint64 size = 1;
    public static final int SIZE_FIELD_NUMBER = 1;
    private long size_;
    public boolean hasSize() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getSize() {
      return size_;
    }
    
    // required bool isDir = 2;
    public static final int ISDIR_FIELD_NUMBER = 2;
    private boolean isDir_;
    public boolean hasIsDir() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getIsDir() {
      return isDir_;
    }
    
    // required string resourceName = 3;
    public static final int RESOURCENAME_FIELD_NUMBER = 3;
    private java.lang.Object resourceName_;
    public boolean hasResourceName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getResourceName() {
      java.lang.Object ref = resourceName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          resourceName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getResourceNameBytes() {
      java.lang.Object ref = resourceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        resourceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      size_ = 0L;
      isDir_ = false;
      resourceName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsDir()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResourceName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, size_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isDir_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getResourceNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, size_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isDir_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getResourceNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rauban.dropandtransfer.protocol.FileTransfer.internal_static_com_rauban_filedropper_protocol_FileDropHeader_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rauban.dropandtransfer.protocol.FileTransfer.internal_static_com_rauban_filedropper_protocol_FileDropHeader_fieldAccessorTable;
      }
      
      // Construct using com.rauban.filedropper.protocol.FileTransfer.FileDropHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        size_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        isDir_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        resourceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader.getDescriptor();
      }
      
      public com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader getDefaultInstanceForType() {
        return com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader.getDefaultInstance();
      }
      
      public com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader build() {
        com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader buildPartial() {
        com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader result = new com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.size_ = size_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isDir_ = isDir_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.resourceName_ = resourceName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader) {
          return mergeFrom((com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader other) {
        if (other == com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader.getDefaultInstance()) return this;
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        if (other.hasIsDir()) {
          setIsDir(other.getIsDir());
        }
        if (other.hasResourceName()) {
          setResourceName(other.getResourceName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasSize()) {
          
          return false;
        }
        if (!hasIsDir()) {
          
          return false;
        }
        if (!hasResourceName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              size_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isDir_ = input.readBool();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              resourceName_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 size = 1;
      private long size_ ;
      public boolean hasSize() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getSize() {
        return size_;
      }
      public Builder setSize(long value) {
        bitField0_ |= 0x00000001;
        size_ = value;
        onChanged();
        return this;
      }
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000001);
        size_ = 0L;
        onChanged();
        return this;
      }
      
      // required bool isDir = 2;
      private boolean isDir_ ;
      public boolean hasIsDir() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getIsDir() {
        return isDir_;
      }
      public Builder setIsDir(boolean value) {
        bitField0_ |= 0x00000002;
        isDir_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsDir() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isDir_ = false;
        onChanged();
        return this;
      }
      
      // required string resourceName = 3;
      private java.lang.Object resourceName_ = "";
      public boolean hasResourceName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getResourceName() {
        java.lang.Object ref = resourceName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          resourceName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setResourceName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        resourceName_ = value;
        onChanged();
        return this;
      }
      public Builder clearResourceName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        resourceName_ = getDefaultInstance().getResourceName();
        onChanged();
        return this;
      }
      void setResourceName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        resourceName_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.rauban.filedropper.protocol.FileDropHeader)
    }
    
    static {
      defaultInstance = new FileDropHeader(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.rauban.filedropper.protocol.FileDropHeader)
  }
  
  public interface FileDropFileOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bytes data = 1;
    boolean hasData();
    com.google.protobuf.ByteString getData();
  }
  public static final class FileDropFile extends
      com.google.protobuf.GeneratedMessage
      implements FileDropFileOrBuilder {
    // Use FileDropFile.newBuilder() to construct.
    private FileDropFile(Builder builder) {
      super(builder);
    }
    private FileDropFile(boolean noInit) {}
    
    private static final FileDropFile defaultInstance;
    public static FileDropFile getDefaultInstance() {
      return defaultInstance;
    }
    
    public FileDropFile getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rauban.dropandtransfer.protocol.FileTransfer.internal_static_com_rauban_filedropper_protocol_FileDropFile_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rauban.dropandtransfer.protocol.FileTransfer.internal_static_com_rauban_filedropper_protocol_FileDropFile_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bytes data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    
    private void initFields() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, data_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rauban.dropandtransfer.protocol.FileTransfer.internal_static_com_rauban_filedropper_protocol_FileDropFile_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rauban.dropandtransfer.protocol.FileTransfer.internal_static_com_rauban_filedropper_protocol_FileDropFile_fieldAccessorTable;
      }
      
      // Construct using com.rauban.filedropper.protocol.FileTransfer.FileDropFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile.getDescriptor();
      }
      
      public com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile getDefaultInstanceForType() {
        return com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile.getDefaultInstance();
      }
      
      public com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile build() {
        com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile buildPartial() {
        com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile result = new com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile) {
          return mergeFrom((com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile other) {
        if (other == com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile.getDefaultInstance()) return this;
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasData()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              data_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bytes data = 1;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.rauban.filedropper.protocol.FileDropFile)
    }
    
    static {
      defaultInstance = new FileDropFile(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.rauban.filedropper.protocol.FileDropFile)
  }
  
  public interface FileDropMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .com.rauban.filedropper.protocol.FileDropFile data = 1;
    boolean hasData();
    com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile getData();
    com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFileOrBuilder getDataOrBuilder();
    
    // optional .com.rauban.filedropper.protocol.FileDropHeader header = 2;
    boolean hasHeader();
    com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader getHeader();
    com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeaderOrBuilder getHeaderOrBuilder();
  }
  public static final class FileDropMessage extends
      com.google.protobuf.GeneratedMessage
      implements FileDropMessageOrBuilder {
    // Use FileDropMessage.newBuilder() to construct.
    private FileDropMessage(Builder builder) {
      super(builder);
    }
    private FileDropMessage(boolean noInit) {}
    
    private static final FileDropMessage defaultInstance;
    public static FileDropMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public FileDropMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rauban.dropandtransfer.protocol.FileTransfer.internal_static_com_rauban_filedropper_protocol_FileDropMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rauban.dropandtransfer.protocol.FileTransfer.internal_static_com_rauban_filedropper_protocol_FileDropMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .com.rauban.filedropper.protocol.FileDropFile data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile getData() {
      return data_;
    }
    public com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFileOrBuilder getDataOrBuilder() {
      return data_;
    }
    
    // optional .com.rauban.filedropper.protocol.FileDropHeader header = 2;
    public static final int HEADER_FIELD_NUMBER = 2;
    private com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader header_;
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader getHeader() {
      return header_;
    }
    public com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeaderOrBuilder getHeaderOrBuilder() {
      return header_;
    }
    
    private void initFields() {
      data_ = com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile.getDefaultInstance();
      header_ = com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (hasData()) {
        if (!getData().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasHeader()) {
        if (!getHeader().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, data_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, header_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, data_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, header_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rauban.dropandtransfer.protocol.FileTransfer.internal_static_com_rauban_filedropper_protocol_FileDropMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rauban.dropandtransfer.protocol.FileTransfer.internal_static_com_rauban_filedropper_protocol_FileDropMessage_fieldAccessorTable;
      }
      
      // Construct using com.rauban.filedropper.protocol.FileTransfer.FileDropMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDataFieldBuilder();
          getHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (dataBuilder_ == null) {
          data_ = com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile.getDefaultInstance();
        } else {
          dataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (headerBuilder_ == null) {
          header_ = com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage.getDescriptor();
      }
      
      public com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage getDefaultInstanceForType() {
        return com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage.getDefaultInstance();
      }
      
      public com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage build() {
        com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage buildPartial() {
        com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage result = new com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (dataBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage) {
          return mergeFrom((com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage other) {
        if (other == com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage.getDefaultInstance()) return this;
        if (other.hasData()) {
          mergeData(other.getData());
        }
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (hasData()) {
          if (!getData().isInitialized()) {
            
            return false;
          }
        }
        if (hasHeader()) {
          if (!getHeader().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile.Builder subBuilder = com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile.newBuilder();
              if (hasData()) {
                subBuilder.mergeFrom(getData());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setData(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader.Builder subBuilder = com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader.newBuilder();
              if (hasHeader()) {
                subBuilder.mergeFrom(getHeader());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setHeader(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .com.rauban.filedropper.protocol.FileDropFile data = 1;
      private com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile data_ = com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile, com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile.Builder, com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFileOrBuilder> dataBuilder_;
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile getData() {
        if (dataBuilder_ == null) {
          return data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      public Builder setData(com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setData(
          com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeData(com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile value) {
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              data_ != com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile.getDefaultInstance()) {
            data_ =
              com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile.newBuilder(data_).mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          dataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile.getDefaultInstance();
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile.Builder getDataBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      public com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFileOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile, com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile.Builder, com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFileOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile, com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile.Builder, com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFileOrBuilder>(
                  data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      
      // optional .com.rauban.filedropper.protocol.FileDropHeader header = 2;
      private com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader header_ = com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader, com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader.Builder, com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeaderOrBuilder> headerBuilder_;
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      public Builder setHeader(com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setHeader(
          com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeHeader(com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              header_ != com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader.getDefaultInstance()) {
            header_ =
              com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      public com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader, com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader.Builder, com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader, com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader.Builder, com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeaderOrBuilder>(
                  header_,
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.rauban.filedropper.protocol.FileDropMessage)
    }
    
    static {
      defaultInstance = new FileDropMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.rauban.filedropper.protocol.FileDropMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rauban_filedropper_protocol_FileDropHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_rauban_filedropper_protocol_FileDropHeader_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rauban_filedropper_protocol_FileDropFile_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_rauban_filedropper_protocol_FileDropFile_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_rauban_filedropper_protocol_FileDropMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_rauban_filedropper_protocol_FileDropMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2com/rauban/filedropper/protocol/FileTr" +
      "ansfer.proto\022\037com.rauban.filedropper.pro" +
      "tocol\"C\n\016FileDropHeader\022\014\n\004size\030\001 \002(\004\022\r\n" +
      "\005isDir\030\002 \002(\010\022\024\n\014resourceName\030\003 \002(\t\"\034\n\014Fi" +
      "leDropFile\022\014\n\004data\030\001 \002(\014\"\217\001\n\017FileDropMes" +
      "sage\022;\n\004data\030\001 \001(\0132-.com.rauban.filedrop" +
      "per.protocol.FileDropFile\022?\n\006header\030\002 \001(" +
      "\0132/.com.rauban.filedropper.protocol.File" +
      "DropHeader"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_rauban_filedropper_protocol_FileDropHeader_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_rauban_filedropper_protocol_FileDropHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_rauban_filedropper_protocol_FileDropHeader_descriptor,
              new java.lang.String[] { "Size", "IsDir", "ResourceName", },
              com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader.class,
              com.rauban.dropandtransfer.protocol.FileTransfer.FileDropHeader.Builder.class);
          internal_static_com_rauban_filedropper_protocol_FileDropFile_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_rauban_filedropper_protocol_FileDropFile_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_rauban_filedropper_protocol_FileDropFile_descriptor,
              new java.lang.String[] { "Data", },
              com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile.class,
              com.rauban.dropandtransfer.protocol.FileTransfer.FileDropFile.Builder.class);
          internal_static_com_rauban_filedropper_protocol_FileDropMessage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_rauban_filedropper_protocol_FileDropMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_rauban_filedropper_protocol_FileDropMessage_descriptor,
              new java.lang.String[] { "Data", "Header", },
              com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage.class,
              com.rauban.dropandtransfer.protocol.FileTransfer.FileDropMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
